lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    token_ttl: 3600
    api_platform:
        check_path: /api/login_check
        username_path: email
        password_path: security.credentials.password