<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7kwC1a2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7kwC1a2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7kwC1a2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7kwC1a2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7kwC1a2\App_KernelDevDebugContainer([
    'container.build_hash' => '7kwC1a2',
    'container.build_id' => '3ea28221',
    'container.build_time' => 1695712944,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7kwC1a2');
