<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9xykvII\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9xykvII/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9xykvII.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9xykvII\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9xykvII\App_KernelDevDebugContainer([
    'container.build_hash' => '9xykvII',
    'container.build_id' => '6d79955a',
    'container.build_time' => 1695934090,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9xykvII');
