<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRsrTYGx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRsrTYGx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRsrTYGx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRsrTYGx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRsrTYGx\App_KernelDevDebugContainer([
    'container.build_hash' => 'RsrTYGx',
    'container.build_id' => '6dbc19c4',
    'container.build_time' => 1695895507,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRsrTYGx');
