name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Demo LS on VPS
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          cd public_html/democd/
          if [ -d "WRA506-Movies-Backend" ]; then
            rm -rf WRA506-Movies-Backend
          fi
          git clone git@github.com:Antoaane/WRA506-Movies-Backend.git
          cd WRA506-Movies-Backend
          git checkout develop
          git pull
          composer install
          composer update
          php bin/console c:c
          php bin/console d:d:c
